// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMExLU3FQRVllWGlReVl4N2dqQ25VeTZ2MXRoaGRPL0sxR3puazVCQWlIaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYlVFUmFaQW52UVozUUFzOENqeGV2NXA1WDR2dEUvWDlLZW1tUHpOTDZrbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtT2dPaGQ5NTJtZC9OTXVYV3RkSUVnNm1SQ2lqb3g4TXJlR0dTblZaKzNrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2QTFwKzZpOEFxcjdxOVZUaHhqMjdDTzJnZFZkN1ZrSUZ1ZFZ2dkI3OFhnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkVNVHBWOUMwajUyZlVKSUtnMXJKYm9QUGJrUExGWm54V1NSb0RESW92a0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlAyZmdsSE4vekh5NUxJUlNKSjRqRTlacVF3dnlsN2d4ZlJwSnl3QWUyVFk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkZBMS9UQ3c0amdNTzN5WUZKcDFVb2w1blhvSTVTSkhDTHZzalVCVDUzND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRHlRN2xUaVB2N2c4S2hFc3JtSFV5UU5uK1MybUMzbHBIN3poUVpPNzB4UT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhEMkFyMTNGMmNvVzZuTG10ajFGY3Vmd0xZUXV2UHFRVVROY0ZhRmZUa2JDaFRJc2IwZkJLbjdqNkdLSENVWVQ4Zk9TdWNIQWZBbXlqV28zRHA5QmhRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAwLCJhZHZTZWNyZXRLZXkiOiJrOHB4STV4ZDBYTHNwNk95Z1JIS0xDZlB6Z2tZTjRlM2JtbjRFL1pSUlRZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJHNjEtU21jd1JuZVVobGgyRDB0SDhBIiwicGhvbmVJZCI6IjNjOWM0NjU1LTY0MzItNGY0MS1iNjViLTY3YjE3M2U4N2Q1ZCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjT1N6TmJzclRpZlhJVHRFWTZMSGRPZ0hxNDA9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSktvM0NUT1hpMTl5elRjWDdvUjVrQ1UwWk1NPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkpSOVpOU1FQIiwibWUiOnsiaWQiOiIyNjM3ODkzMzE5MjI6N0BzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJLaWNoeUJvaSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUGVvaU5zRUVOYnZpcmdHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUThrbUxWSi85dlU4VGNqa3UxVVhzMVNzRnM0VVVab2tydTJUZ2xmMERtYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiSGlENzVQcG9DdUoxTktJSEJMTmw4VG5CQUxQUjRZbVBzTG50MmVLajJaT0JEMmhxWlNWUjBjRGkvbzJxOWVQOUVvVUtHTUJ6L1EzTDdaMFl1OWZORHc9PSIsImRldmljZVNpZ25hdHVyZSI6IkFjUWNtemJndkZ6cnRTVFBxZVFoeWhsUnczMmxtdnFXR1RrcUFQdEprQTF6VU1veHA5WnZWdnN2dktEUU91c1lVK202b3VsVnRQelV3N2pGc0JLT2dnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjYzNzg5MzMxOTIyOjdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVVBKSmkxU2YvYjFQRTNJNUx0VkY3TlVyQmJPRkZHYUpLN3RrNEpYOUE1biJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyODIzMTM5Nn0=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©Baraka Bega",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "255762190568",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
